name: Policy evaluation 

on:
  push:
    tags: ["*"]
    branches:
      - main
  pull_request:
    branches: ["**"]

env:
  REGISTRY: docker.io
  REGISTRY_USER: felipecruz1638514

jobs:
  build-analyze-push:
    name: Evaluate policies
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Evaluate already indexed image
        uses: felipecruz91/scout-action@main
        with:
          command: policy
          image: "dockerscoutpolicytest/customers-api-service:0.0.12"
          organization: "dockerscoutpolicytest"

      - name: Evaluate already indexed image with timeout
        uses: felipecruz91/scout-action@main
        with:
          command: policy
          image: "dockerscoutpolicytest/customers-api-service:0.0.12"
          organization: "dockerscoutpolicytest"

      - name: Evaluate already indexed image with platform
        uses: felipecruz91/scout-action@main
        with:
          command: policy
          image: "dockerscoutpolicytest/customers-api-service:0.0.12"
          organization: "dockerscoutpolicytest"
          platform: "linux/amd64"

      - name: Evaluate already indexed image with exit code true
        uses: felipecruz91/scout-action@main
        with:
          command: policy
          image: "dockerscoutpolicytest/customers-api-service:0.0.12"
          organization: "dockerscoutpolicytest"
          exit-code: true # Fail the build if the policies are not met
